# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    labels:
      - "npm"
      - "dependencies"
    reviewers:
      - "zwilla"
    day: "monday"
    time: "00:00"
    timezone: "Europe/Berlin"
    
      
      
# Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      open-pull-requests-limit: 5
   reviewers:
      - "zwilla"
   day: "monday"
   time: "02:00"
   timezone: "Europe/Berlin"
